name: Tests

on:
  push:
    branches: [ "*" ]  # Run on pushes to all branches
  pull_request:
    branches: [ "*" ]  # Run on PRs to all branches

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .

    - name: Install test dependencies
      run: |
        pip install pyfixest pandas scikit-learn

    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short

    - name: Run specific fixed effects tests
      run: |
        python -m pytest tests/test_fe.py -v

  test-fast:
    # Quick test job for faster feedback
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .
        pip install pyfixest pandas scikit-learn

    - name: Run minimal test suite
      run: |
        python -m pytest tests/test_linear.py tests/test_fe.py::test_minimal_example -v
